export const authConstant ={
    LOGIN_REQUEST:"LOGIN_REQUEST",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_FAILURE:"LOGIN_FAILURE",
    
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
}

export const categoryConstant={
    GETALLCATEGORY_REQUEST:"GETALLCATEGORY_REQUEST",
    GETALLCATEGORY_SUCCESS:"GETALLCATEGORY_SUCCESS",
    GETALLCATEGORY_FAILURE:"GETALLCATEGORY_FAILURE"
   

}
export const productsConstant ={
    GET_ALL_PRODUCTSBY_SLUG :"GET_ALL_PRODUCTSBY_SLUG",
    GET_ALL_PRODUCTS_PAGE_REQUEST:"GET_ALL_PRODUCTS_PAGE_REQUEST",
    GET_ALL_PRODUCTS_PAGE_SUCCESS:"GET_ALL_PRODUCTS_PAGE_SUCCESS",
    GGET_ALL_PRODUCTS_PAGE_FAILURE:"GET_ALL_PRODUCTS_PAGE_FAILURE",
    
GET_PRODUCT_DETAILS_BY_ID_REQUEST:"GET_PRODUCT_DETAILS_BY_ID_REQUEST",
GET_PRODUCT_DETAILS_BY_ID_SUCCESS:"GET_PRODUCT_DETAILS_BY_ID_SUCCESS",
GET_PRODUCT_DETAILS_BY_ID_FAILURE:"GET_PRODUCT_DETAILS_BY_ID_FAILURE",

}
