
export const categoryConstant={
    GETALLCATEGORY_REQUEST:"GETALLCATEGORY_REQUEST",
    GETALLCATEGORY_SUCCESS:"GETALLCATEGORY_SUCCESS",
    GETALLCATEGORY_FAILURE:"GETALLCATEGORY_FAILURE",
    
    ADDNEW_CATEGORY_REQUEST:"ADDNEW_CATEGORY_REQUEST",
    ADDNEW_CATEGORY_SUCCESS:"ADDNEW_CATEGORY_SUCCESS",
    ADDNEW_CATEGORY_FAILURE:"ADDNEW_CATEGORY_FAILURE",

}
export const productsConstant ={
    GET_ALL_PRODUCTS_REQUEST:"GET_ALL_PRODUCTS_REQUEST",
    GET_ALL_PRODUCTS_SUCCESS:"GET_ALL_PRODUCTS_SUCCESS",
    GET_ALL_PRODUCTS_FAILURE:"GET_ALL_PRODUCTS_FAILURE"
}
